# Generated by Django 5.1.6 on 2025-02-12 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kitoblar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavha', models.CharField(max_length=200)),
                ('muallif', models.CharField(max_length=150)),
                ('nashriyot', models.CharField(max_length=200)),
                ('yili', models.IntegerField()),
                ('isbn', models.IntegerField()),
            ],
        ),
    ]
